### ISSUE TITLE
Cannot build with libgit2 1.9.0

### ISSUE THREAD

**Issue by rhelmot** [edo9300/edopro#284]
Fails as such:

```
In file included from ../gframe/repo_manager.h:14,                                                                                                                                                                                            
                 from ../gframe/data_handler.h:5,                                                                                                                                                                                             
                 from ../gframe/gframe.cpp:25:
/usr/include/git2/version.h:16:1: error: 'GIT_BEGIN_DECL' does not name a type
```

I believe you need to `#include <git2/common.h>` before using version.h.

**Comment by edo9300** [comment]
Fixed in https://github.com/edo9300/edopro/commit/f8ddbfff51231827a8dd1dcfcb2dda85f50a56d9, and also opened an issue in the upstream library, https://github.com/libgit2/libgit2/issues/7027, since this is a problem on their end

**Comment by rhelmot** [comment]
Works for me. Thanks!
