### ISSUE TITLE
Issue Installing on Kubuntu 19.10

### ISSUE THREAD

**Issue by Mindforms** [edo9300/edopro#194]
I'm trying to install the latest build on my Kubuntu 19.10 computer. I installed all prerequisites and dependencies (most of which were already installed on my system)... but when I get to the 'Building' step, the "make" command yields the following error:

```
In file included from ../gframe/CGUISkinSystem/CConfigMap.cpp:1:
../gframe/CGUISkinSystem/CConfigMap.h:4:10: fatal error: irrMap.h: No such file or directory
    4 | #include <irrMap.h>
      |          ^~~~~~~~~~
compilation terminated.
make[1]: *** [ygoprodll.make:272: ../obj/Debug/ygoprodll/CConfigMap.o] Error 1
make: *** [Makefile:62: ygoprodll] Error 2
make: *** Waiting for unfinished jobs....
```

That is quite strange, because I do have the irrMap.h file installed in /usr/include/irrlicht. Am I doing something wrong?
